# Generated by Django 2.2 on 2020-08-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('fone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('fone', models.CharField(max_length=14)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Cliente')),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Cobrador')),
            ],
        ),
    ]
