# Generated by Django 2.2 on 2020-08-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descricao', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('codigo', models.CharField(max_length=8, null=True, unique=True)),
                ('fone', models.CharField(blank=True, max_length=14, null=True)),
                ('detalhe', models.CharField(default='', max_length=150)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='C:\\Users\\Lucas\\uchoa-app\\uchoa-app\\static/images')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('nome', models.CharField(default='', max_length=200)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('fone', models.CharField(blank=True, max_length=14, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_emprestimo', models.CharField(choices=[('di', 'Diário'), ('se', 'Semanal'), ('qu', 'Quinzenal'), ('me', 'Mensal')], default='di', max_length=10)),
                ('atraso', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Cliente')),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Cobrador')),
            ],
        ),
        migrations.CreateModel(
            name='ValeRua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale_vale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Cobrador')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Emprestimo')),
            ],
        ),
    ]
