# Generated by Django 2.2 on 2020-10-01 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descricao', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('codigo', models.CharField(max_length=8, null=True, unique=True)),
                ('fone', models.CharField(blank=True, max_length=14, null=True)),
                ('detalhe', models.CharField(default='', max_length=150)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='C:\\Users\\maisa\\uchoa-app\\static/images')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Area')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('nome', models.CharField(default='', max_length=200)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('fone', models.CharField(blank=True, max_length=14, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_emprestimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_emprestimo', models.CharField(choices=[('di', 'Diário'), ('se', 'Semanal'), ('qu', 'Quinzenal'), ('me', 'Mensal')], default='di', max_length=10)),
                ('falta', models.BooleanField(default=False)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_start', models.DateField(default=datetime.date(2020, 10, 1))),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='app_uchoa.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ValeRua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale_vale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Cobrador')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cobrador'), (2, 'Dono')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 10, 1))),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='app_uchoa.Emprestimo')),
            ],
        ),
    ]
