# Generated by Django 2.2 on 2020-08-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uchoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='cobrador',
        ),
    ]
