# Generated by Django 2.2 on 2020-08-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uchoa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='valor',
        ),
        migrations.AddField(
            model_name='cliente',
            name='doc_file',
            field=models.FileField(default=0, upload_to='C:\\Users\\Usuário\\app\\uchoa-app\\static/uploads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='tipo_emprestimo',
            field=models.CharField(choices=[('di', 'Diário'), ('se', 'Semanal'), ('qu', 'Quinzenal'), ('me', 'Mensal')], default='di', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_emprestimo',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('valor_parcela', models.FloatField(default=0.0)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Emprestimo')),
            ],
        ),
    ]
