# Generated by Django 2.2 on 2020-08-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uchoa', '0002_auto_20200813_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='descricao',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='detalhe',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='atraso',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\Usuário\\app\\uchoa-app\\static/uploads'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='cobrador',
            name='fone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_emprestimo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ValeRua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale_vale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uchoa.Cobrador')),
            ],
        ),
    ]
