# Generated by Django 2.2 on 2020-08-31 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_uchoa', '0003_emprestimo_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='date_start',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 31)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Cobrador'), (2, 'Dono')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
