# Generated by Django 2.2 on 2020-10-02 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uchoa', '0004_auto_20200831_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='date_start',
            field=models.DateField(default=datetime.date(2020, 10, 2)),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 2)),
        ),
    ]
