# Generated by Django 2.2 on 2020-10-01 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uchoa', '0004_auto_20200831_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\maisa\\uchoa-app\\static/images'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='date_start',
            field=models.DateField(default=datetime.date(2020, 10, 1)),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 1)),
        ),
    ]
